# Generated by Django 4.0.1 on 2022-01-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0024_delete_nonfinancialdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_person', models.CharField(max_length=255)),
                ('redeemed_status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed')], default=('pending', 'Pending'), max_length=255)),
                ('contact_information', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonetaryPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_person', models.CharField(max_length=255)),
                ('redeemed_status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed')], default=('pending', 'Pending'), max_length=255)),
                ('contact_information', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('amount_pledge', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberMonetaryPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed')], default=('pending', 'Pending'), max_length=255)),
                ('amount_pledge', models.FloatField(default=0.0)),
                ('contact_information', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pledge_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberMaterialPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed')], default=('pending', 'Pending'), max_length=255)),
                ('amount_pledge', models.FloatField(default=0.0)),
                ('contact_information', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('pledge_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
