# Generated by Django 4.0.1 on 2022-01-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermaterialpledge',
            old_name='amount_pledge',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='membermonetarypledge',
            old_name='amount_pledge',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='materialpledge',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='materialpledge',
            name='amount_pledged',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='membermaterialpledge',
            name='amount_pledged',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='membermonetarypledge',
            name='amount_pledged',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monetarypledge',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monetarypledge',
            name='amount_pledged',
            field=models.FloatField(default=0.0),
        ),
    ]
