# Generated by Django 4.0.1 on 2022-01-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0006_remove_membermaterialpledge_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialpledge',
            name='amount_pledged',
        ),
        migrations.RemoveField(
            model_name='membermaterialpledge',
            name='amount_pledged',
        ),
    ]
