# Generated by Django 4.0.1 on 2022-01-26 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0010_remove_membermaterialpledge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermaterialpledge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membermaterialpledge',
            name='item',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membermaterialpledge',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
