# Generated by Django 4.0.1 on 2022-01-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0023_remove_member_welfare_contributions_and_more'),
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WelfareContributions',
            new_name='WelfareContribution',
        ),
    ]
