# Generated by Django 4.0.1 on 2022-01-17 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0002_rename_welfarecontributions_welfarecontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfare',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 17, 9, 8, 33, 450324, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welfare',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
