# Generated by Django 4.0.1 on 2022-04-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0004_welfaremembershiplevy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfare',
            name='deadline',
            field=models.DateField(),
        ),
    ]
