# Generated by Django 4.0.1 on 2022-04-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialPledge',
            new_name='ItemPledge',
        ),
        migrations.RenameModel(
            old_name='MemberMaterialPledge',
            new_name='MemberItemPledge',
        ),
    ]
