# Generated by Django 4.0.1 on 2022-04-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0002_rename_materialpledge_itempledge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermonetarypledge',
            name='contact_information',
        ),
    ]
