# Generated by Django 4.0.1 on 2022-01-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0004_materialpledge_amount_pledged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialpledge',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='membermaterialpledge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='membermaterialpledge',
            name='item',
        ),
        migrations.RemoveField(
            model_name='membermaterialpledge',
            name='quantity',
        ),
    ]
