# Generated by Django 4.0.1 on 2022-04-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0005_rename_person_itempledge_pledge_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetarypledge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
