# Generated by Django 4.0.1 on 2022-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0006_monetarypledge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempledge',
            name='email',
            field=models.EmailField(default='me@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempledge',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberitempledge',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberitempledge',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membermonetarypledge',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membermonetarypledge',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monetarypledge',
            name='email',
            field=models.EmailField(default='me@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monetarypledge',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
