# Generated by Django 4.0.1 on 2022-01-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0007_remove_materialpledge_amount_pledged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermonetarypledge',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='monetarypledge',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
