# Generated by Django 4.0.1 on 2022-04-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0008_alter_itempledge_email_alter_itempledge_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempledge',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='memberitempledge',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='membermonetarypledge',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monetarypledge',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
