# Generated by Django 4.0.1 on 2022-04-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0009_alter_itempledge_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempledge',
            name='contact_information',
        ),
        migrations.RemoveField(
            model_name='memberitempledge',
            name='contact_information',
        ),
        migrations.RemoveField(
            model_name='monetarypledge',
            name='contact_information',
        ),
    ]
