# Generated by Django 4.0.1 on 2022-02-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0012_remove_materialpledge_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermonetarypledge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='membermonetarypledge',
            name='item',
        ),
        migrations.RemoveField(
            model_name='membermonetarypledge',
            name='quantity_pledged',
        ),
        migrations.RemoveField(
            model_name='membermonetarypledge',
            name='quantity_redeemed',
        ),
        migrations.RemoveField(
            model_name='monetarypledge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='monetarypledge',
            name='item',
        ),
        migrations.RemoveField(
            model_name='monetarypledge',
            name='quantity_pledged',
        ),
        migrations.RemoveField(
            model_name='monetarypledge',
            name='quantity_redeemed',
        ),
    ]
