# Generated by Django 4.0.1 on 2022-04-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmonetarycontribution_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDocuments',
            new_name='ProjectDocument',
        ),
        migrations.RenameModel(
            old_name='ProjectNotes',
            new_name='ProjectNote',
        ),
        migrations.AlterModelOptions(
            name='projectdocument',
            options={'verbose_name': 'Project Note', 'verbose_name_plural': 'Project Notes'},
        ),
        migrations.AlterModelOptions(
            name='projectinventory',
            options={'verbose_name': 'Project Inventory', 'verbose_name_plural': 'Project Inventories'},
        ),
        migrations.AlterModelOptions(
            name='projectnote',
            options={'verbose_name': 'Project Note', 'verbose_name_plural': 'Project Notes'},
        ),
    ]
