# Generated by Django 4.0.1 on 2022-04-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_projectdocuments_projectdocument_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmonetarycontribution',
            options={'verbose_name': 'Project Monetary Contribution', 'verbose_name_plural': 'Project Monetary Contributions'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='objective',
        ),
    ]
