# Generated by Django 4.0.1 on 2022-04-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_created_on_project_updated_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectInventory',
            new_name='ProjectItemContribution',
        ),
        migrations.AlterModelOptions(
            name='projectitemcontribution',
            options={'verbose_name': 'Project Item Contribution', 'verbose_name_plural': 'Project Item Contributions'},
        ),
    ]
