# Generated by Django 4.0.1 on 2022-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_projectinventory_projectitemcontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='item',
            field=models.CharField(default='iron rods', max_length=255),
            preserve_default=False,
        ),
    ]
