# Generated by Django 4.0.1 on 2022-04-15 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectexpense_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 15, 17, 1, 46, 826778, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
