# Generated by Django 4.0.1 on 2022-04-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('primary_phone', models.CharField(max_length=255)),
                ('secondary_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city_or_town', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('occupation', models.CharField(choices=[('teacher', 'Teacher'), ('lecturer', 'Lecturer'), ('nurse', 'Nurse'), ('doctor', 'Doctor')], max_length=255)),
                ('sector', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=255)),
                ('education_level', models.CharField(choices=[('no-school', 'Not Applicable'), ('primary', 'Primary'), ('jhs', 'JHS'), ('shs', 'SHS'), ('vocational', 'Vocational'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('diploma', 'Diploma'), ('hnd', 'HND'), ('degree', 'Degree'), ('masters', 'masters'), ('phd', 'PHD')], max_length=255)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('co-habitating', 'Co-habitating'), ('engaged', 'Engaged'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('religious', 'religious')], default=('single', 'Single'), max_length=20)),
                ('father_name', models.CharField(max_length=255)),
                ('father_hometown', models.CharField(max_length=255)),
                ('father_living_status', models.CharField(choices=[('deceased', 'Deceased'), ('alive', 'Alive')], default=None, max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_hometown', models.CharField(max_length=255)),
                ('mother_living_status', models.CharField(choices=[('deceased', 'Deceased'), ('alive', 'Alive')], default=None, max_length=255)),
                ('next_of_kin_name', models.CharField(max_length=255)),
                ('next_of_kin_relationship', models.CharField(choices=[('brother', 'Brother'), ('sister', 'Sister'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('cousin', 'Cousin'), ('friend', 'Friend')], max_length=255)),
                ('next_of_kin_primary_phone', models.CharField(max_length=255)),
                ('next_of_kin_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('next_of_kin_location', models.CharField(blank=True, max_length=255)),
                ('emergency_name', models.CharField(max_length=255)),
                ('emergency_primary_phone', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, default='default_profile_photo.jpg', null=True, upload_to='profile_photos')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('organisations', models.ManyToManyField(blank=True, to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='MemberReligiousCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baptism_status', models.BooleanField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('baptism_location', models.CharField(blank=True, max_length=255, null=True)),
                ('baptised_by', models.CharField(blank=True, max_length=255, null=True)),
                ('holy_communion_status', models.BooleanField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=True)),
                ('holy_communion_date', models.DateField(blank=True, null=True)),
                ('holy_communion_location', models.CharField(blank=True, max_length=255, null=True)),
                ('holy_communion_given_by', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation_status', models.BooleanField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('confirmation_location', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'verbose_name': 'Member Christian Information',
                'verbose_name_plural': 'Members Christian Information',
            },
        ),
    ]