# Generated by Django 4.0.1 on 2022-01-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0023_remove_member_welfare_contributions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonFinancialDonation',
        ),
    ]
