# Generated by Django 4.0.1 on 2022-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0029_member_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_profile_photo.jpg', upload_to='profile_photos'),
        ),
    ]
