# Generated by Django 4.0.1 on 2022-04-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welfarecontribution',
            name='welfare',
        ),
    ]
