# Generated by Django 4.0.1 on 2022-04-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0002_remove_welfarecontribution_welfare'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfarecontribution',
            name='welfare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='welfare_contributions', to='welfare.welfare'),
            preserve_default=False,
        ),
    ]
