# Generated by Django 4.0.1 on 2022-04-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0003_welfarecontribution_welfare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welfaremembershiplevy',
            old_name='month_levy_paid',
            new_name='month_welfare_paid',
        ),
    ]
