# Generated by Django 4.0.1 on 2022-04-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchsettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsetup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchsetup',
            name='short_name',
            field=models.CharField(default='St. Ralph', max_length=12),
            preserve_default=False,
        ),
    ]
