# Generated by Django 4.0.1 on 2022-04-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='created_on_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='updated_on_date',
            new_name='updated_on',
        ),
    ]
