# Generated by Django 4.0.1 on 2022-01-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0024_delete_nonfinancialdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('organisation_description', models.TextField(blank=True, null=True)),
                ('president', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.member')),
            ],
        ),
    ]