# Generated by Django 4.0.1 on 2022-01-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchorganisation',
            name='president',
        ),
    ]