# Generated by Django 4.0.1 on 2022-04-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_active_activateuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activateuser',
            old_name='link',
            new_name='token',
        ),
    ]
