# Generated by Django 4.0.1 on 2022-01-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershipmonthlylevy_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='april_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='august_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='december_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='february_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='january_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='july_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='june_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='march_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='may_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='november_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='october_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='september_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
