# Generated by Django 4.0.1 on 2022-01-08 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_memberreligiouscv_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmonthlylevy',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipmonthlylevy',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
