# Generated by Django 4.0.1 on 2022-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_member_created_on_member_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberreligiouscv',
            name='baptism_status',
            field=models.BooleanField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=True),
        ),
        migrations.AlterField(
            model_name='memberreligiouscv',
            name='confirmation_status',
            field=models.BooleanField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=True),
        ),
        migrations.AlterField(
            model_name='memberreligiouscv',
            name='holy_communion_status',
            field=models.BooleanField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=True),
        ),
    ]
