# Generated by Django 4.0.1 on 2022-01-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_alter_memberreligiouscv_baptism_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipmonthlylevy',
            old_name='april_payment',
            new_name='month_levy_paid',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='august_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='december_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='february_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='january_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='july_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='june_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='march_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='may_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='november_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='october_payment',
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='september_payment',
        ),
        migrations.AddField(
            model_name='membershipmonthlylevy',
            name='month',
            field=models.IntegerField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='total',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
