# Generated by Django 4.0.1 on 2022-01-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_rename_april_payment_membershipmonthlylevy_month_levy_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=2022, max_length=100, null=True),
        ),
    ]
