# Generated by Django 4.0.1 on 2022-01-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_membershipmonthlylevy_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDailyActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_registered_today', models.IntegerField(default=0, editable=False, null=True)),
                ('total_monies_collected_today', models.FloatField(default=0, editable=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='membershipmonthlylevy',
            name='total',
        ),
    ]
