# Generated by Django 4.0.1 on 2022-01-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_trytest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
    ]
