# Generated by Django 4.0.1 on 2022-01-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_alter_membershipmonthlylevy_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TryTest',
        ),
    ]
