# Generated by Django 4.0.1 on 2022-01-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_delete_trytest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackdailyactivities',
            name='total_levies_collected_today',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
    ]
