# Generated by Django 4.0.1 on 2022-01-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_alter_member_father_living_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mother_living_status',
            field=models.BooleanField(choices=[('deceased', 'Deceased'), ('alive', 'Alive')], default=None),
        ),
    ]
