# Generated by Django 4.0.1 on 2022-01-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_alter_member_mother_living_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='father_living_status',
            field=models.CharField(choices=[('deceased', 'Deceased'), ('alive', 'Alive')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='mother_living_status',
            field=models.CharField(choices=[('deceased', 'Deceased'), ('alive', 'Alive')], default=None, max_length=255),
        ),
    ]
