# Generated by Django 4.0.1 on 2022-01-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0020_alter_membershipmonthlylevy_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welfare_title', models.CharField(max_length=255)),
                ('welfare_description', models.TextField(blank=True, null=True)),
                ('amount_contributed', models.FloatField(blank=True, default=0, null=True)),
                ('deadline', models.DateTimeField()),
                ('members', models.ManyToManyField(to='membership.Member')),
            ],
        ),
        migrations.DeleteModel(
            name='TrackDailyActivities',
        ),
        migrations.AlterField(
            model_name='membershipmonthlylevy',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
    ]
