# Generated by Django 4.0.1 on 2022-01-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0022_alter_memberreligiouscv_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='welfare_contributions',
        ),
        migrations.DeleteModel(
            name='WelfareSupport',
        ),
    ]
