# Generated by Django 4.0.1 on 2022-04-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_churchorganisation_organisation_name'),
        ('membership', '0031_alter_member_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='organisations',
            field=models.ManyToManyField(blank=True, to='groups.Group'),
        ),
    ]