# Generated by Django 4.0.1 on 2022-01-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0031_alter_member_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='marital_status',
        ),
    ]
