# Generated by Django 4.0.1 on 2022-01-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdonation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
