# Generated by Django 4.0.1 on 2022-04-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermonetarydonation',
            old_name='donor',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='membermonetarydonation',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='membermonetarydonation',
            name='payment_method',
        ),
    ]
