# Generated by Django 4.0.1 on 2022-04-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_rename_donor_membermonetarydonation_member_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalMaterialDonation',
        ),
        migrations.DeleteModel(
            name='ExternalMonetaryDonation',
        ),
        migrations.RenameField(
            model_name='membermaterialdonation',
            old_name='donor',
            new_name='member',
        ),
    ]
