# Generated by Django 4.0.1 on 2022-04-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('donations', '0003_delete_externalmaterialdonation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberMaterialDonation',
            new_name='MemberItemDonation',
        ),
    ]
