# Generated by Django 4.0.1 on 2022-01-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0026_remove_member_organisations_member_organisations'),
        ('donations', '0003_alter_financialdonation_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMaterialDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'verbose_name': 'Material Donation',
                'verbose_name_plural': 'Material Donations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberMonetaryDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_donated', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money')], default=None, max_length=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FinancialDonation',
        ),
        migrations.DeleteModel(
            name='NonFinancialDonation',
        ),
    ]
