# Generated by Django 4.0.1 on 2022-04-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_rename_membermaterialdonation_memberitemdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonetaryDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
