# Generated by Django 4.0.1 on 2022-04-11 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_monetarydonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetarydonation',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='contact_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='donor',
            field=models.CharField(default=datetime.datetime(2022, 4, 11, 22, 14, 20, 540672, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
