# Generated by Django 4.0.1 on 2022-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_monetarydonation_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberitemdonation',
            options={'ordering': ('created_on', 'updated_on')},
        ),
        migrations.AlterModelOptions(
            name='membermonetarydonation',
            options={'ordering': ('created_on', 'updated_on')},
        ),
        migrations.AlterField(
            model_name='monetarydonation',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monetarydonation',
            name='contact_information',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
