# Generated by Django 4.0.1 on 2022-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_memberitemdonation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monetarydonation',
            name='contact_information',
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='phone_number',
            field=models.CharField(default=5902340922, max_length=20),
            preserve_default=False,
        ),
    ]
