# Generated by Django 4.0.1 on 2022-05-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_remove_monetarydonation_contact_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermonetarydonation',
            old_name='amount_donated',
            new_name='amount',
        ),
    ]
