# Generated by Django 4.0.1 on 2022-04-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_offering', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_services.churchservice')),
                ('type_of_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerings.offeringtype')),
            ],
        ),
    ]