# Generated by Django 4.0.1 on 2022-04-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offering',
            old_name='purpose',
            new_name='service',
        ),
    ]
