# Generated by Django 4.0.1 on 2022-04-05 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchevent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 10, 16, 19, 669869, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='churchevent',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
