# Generated by Django 4.0.1 on 2022-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevents', '0002_churchevent_end_date_churchevent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchevent',
            name='type',
            field=models.CharField(choices=[('one-time', 'One-Time'), ('recurring', 'Recurring')], default=None, max_length=20),
        ),
    ]
